name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    uses: jarero321/shared-workflows/.github/workflows/npm-publish.yml@main
    with:
      package-manager: 'bun'
      build-command: 'bun run build'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
